// <auto-generated />
namespace nCode.CMS.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingContentBlocks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingContentBlocks));
        
        string IMigrationMetadata.Id
        {
            get { return "201505011345414_AddingContentBlocks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
