<?xml version="1.0" encoding="utf-8"?><Database Name="ncode_dk" EntityNamespace="nCode.CRM" ContextNamespace="nCode.CRM" Class="CrmModel" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.CRM_CustomerContacts" Member="CustomerContacts">
    <Type Name="CustomerContact">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(255) NULL" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NULL" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255) NULL" CanBeNull="true" />
      <Association Name="Customer_CustomerContact" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(20) NULL" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Web" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(255) NULL" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255) NULL" CanBeNull="true" />
      <Association Name="Customer_CustomerContact" Member="Contacts" ThisKey="ID" OtherKey="CustomerID" Type="CustomerContact" />
      <Association Name="Customer_CustomerProperty" Member="Properties" ThisKey="ID" OtherKey="CustomerID" Type="CustomerProperty" />
      <Association Name="CustomerGroup_Customer" Member="Group" ThisKey="GroupCode" OtherKey="Code" Type="CustomerGroup" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_CustomerProperties" Member="CustomerProperties">
    <Type Name="CustomerProperty">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Customer_CustomerProperty" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_CustomerGroups" Member="CustomerGroups">
    <Type Name="CustomerGroup">
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>