<?xml version="1.0" encoding="utf-8"?><Database Name="ncode_dk" EntityNamespace="nCode" ContextNamespace="nCode" Class="SystemModel" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.System_MetadataDescriptors" Member="MetadataDescriptorEntities">
    <Type Name="MetadataDescriptorEntity">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectTypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DisplayIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayText" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayMode" Type="global::nCode.Metadata.MetadataEditControlViewMode" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditControlPath" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EditControlArguments" Type="System.String" DbType="NVarChar(255) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_MetadataProperties" Member="GenericMetadataProperties">
    <Type Name="GenericMetadataProperty">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectTypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ObjectID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Key" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>