<?xml version="1.0" encoding="utf-8"?><Database Name="ncode_dk" EntityNamespace="nCode.CMS" ContextNamespace="nCode.CMS" Class="CmsModel" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="CMS_ContentBlock" Member="ContentBlocks">
    <Type Name="ContentBlock">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Code" Storage="_Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="ContentBlock_ContentBlockLocalization" Member="Localizations" ThisKey="ID" OtherKey="ContentBlockID" Type="ContentBlockLocalization" />
    </Type>
  </Table>
  <Table Name="CMS_ContentBlockLocalization" Member="ContentBlockLocalizations">
    <Type Name="ContentBlockLocalization">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContentBlockID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Culture" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ContentBlock_ContentBlockLocalization" Member="ContentBlock" ThisKey="ContentBlockID" OtherKey="ID" Type="ContentBlock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CMS_News" Member="News">
    <Type Name="News">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Language" Member="Culture" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Introduction" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Text" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ValidFrom" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ValidTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CMS_NewsGroup" Member="NewsGroups">
    <Type Name="NewsGroup">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CMS_NewsInNewsGroup" Member="NewsInNewsGroups">
    <Type Name="NewsInNewsGroup">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NewsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NewsGroupID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="News_CMS_NewsInNewsGroup" Member="News" ThisKey="NewsID" OtherKey="ID" Type="News" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NewsGroup_CMS_NewsInNewsGroup" Member="NewsGroup" ThisKey="NewsGroupID" OtherKey="ID" Type="NewsGroup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>